name: Service Template Check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Test
        run: make test
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          RELEASE_BRANCHES: master
          DEFAULT_BUMP: PATCH



